version: '3'
services:
    nginx:
        container_name: nginx
        build:
            context: ./etc/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./src/public:/var/www/html
            - ./etc/nginx/logs/:/var/log/nginx/
            - ./etc/nginx/sites-enabled/:/etc/nginx/conf.d/
        depends_on:
            - php-fpm
            - mysql
    php-fpm:
        container_name: php-fpm
        build:
            context: ./etc/php-fpm
            dockerfile: Dockerfile
        expose:
            - "9000"
        restart: always
        volumes:
            - ./src/public:/var/www/html